# Generated by Django 2.2.7 on 2019-11-16 19:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 11, 16, 19, 1, 13, 576567, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 19, 1, 26, 714098, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
