# Generated by Django 2.2.7 on 2019-11-25 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_portfolio_stockdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='company_name',
            field=models.CharField(default='aapl', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='created_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='base_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='current_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='stock_meta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Stock'),
            preserve_default=False,
        ),
    ]
