# Generated by Django 2.2.7 on 2019-12-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191125_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_template', models.TextField(max_length=1000)),
                ('email_template_name', models.CharField(max_length=25)),
            ],
        ),
    ]
