# Generated by Django 2.2.7 on 2019-12-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emailtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='email_template',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='email_template_name',
            field=models.CharField(max_length=250),
        ),
    ]
