# Generated by Django 2.2.7 on 2019-12-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191202_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='email_template',
            field=models.TextField(max_length=50000),
        ),
    ]
