# Generated by Django 3.0 on 2019-12-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191202_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='email_type',
            field=models.CharField(choices=[('WM', 'Welcome mail'), ('PM', 'portfolio mail'), ('WSM', 'Wishlist mail'), ('PRM', 'Password Reset mail')], default='PM', max_length=10),
            preserve_default=False,
        ),
    ]
