# Generated by Django 3.0 on 2019-12-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_emailtemplate_email_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_image',
            field=models.URLField(default='upload.wikimedia.org/wikipedia/commons/thumb/9/95/Infosys_logo.svg/440px-Infosys_logo.svg.png'),
            preserve_default=False,
        ),
    ]
