# Generated by Django 3.0 on 2019-12-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191213_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='quantity',
            field=models.FloatField(default=1.0),
        ),
    ]
